services:
  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    restart: always
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    environment:
      - SECRET=${SECRET}
      - TAG=${TAG}
      - WORKERS=${WORKERS}
    volumes:
      - ./proxy-config:/data